wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.13
    start_time: 1668446285.42712
    t:
      1:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 63
      - 74
      2:
      - 1
      - 5
      - 41
      - 53
      - 55
      - 63
      - 74
      3:
      - 23
      4: 3.7.13
      5: 0.13.5
      8:
      - 5
